config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :howtos
  get 'dashboard/index'
  get 'dashboard/credits'
  get 'dashboard/statistic'
  get 'dashboard/chart'
  get 'dashboard/authorization'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :inca_receipts do
    collection do
      get :billdownload
    end
  end

  resources :inca_subscriptions do
    collection do
      get :billdownload
    end
  end
end

app/models/inca_subscription.rb
class IncaSubscription < ApplicationRecord
  belongs_to :inca_office
  belongs_to :subscription_typology
  belongs_to :sex
  belongs_to :company_typology, optional: true
  belongs_to :work_qualify, optional: true
  belongs_to :work_level, optional: true
  belongs_to :work_worker, optional: true
  belongs_to :payment_typology
  belongs_to :category
  belongs_to :subscription_year
  belongs_to :inca_practise
  belongs_to :privacy_one
  belongs_to :privacy_two
  belongs_to :privacy_three
  belongs_to :user

  has_one_attached :pdf

  before_create :set_name
  def set_name
    last_name = IncaSubscription.maximum(:name)
    self.name = last_name.to_i + 1
  end

  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true
  validates :sex_id, presence: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :customer_nationality, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :inca_office_id, presence: true
  validates :inca_practise_id, presence: true
  validates :subscription_year, presence: true
  validates :category_id, presence: true
  validates :privacy_one, presence: true
  validates :privacy_two, presence: true
  validates :privacy_three, presence: true
  validates :cancellation_reason, if: -> { cancellation == true }, presence: true
end

app/controllers/inca_subscriptions_controller.rb
class IncaSubscriptionsController < ApplicationController
  load_and_authorize_resource

  before_action :set_inca_subscription, only: %i[show edit update destroy]

  def index
    @user = current_user
    @q = IncaSubscription.ransack(params[:q])
    @inca_subscriptions = @q.result(didtinct: true).order(name: 'DESC')
                            .paginate(page: params[:page], per_page: 10)
    @tariffs = Tariff.all.order(position: 'ASC')
  end

  def show
    @tariffs = Tariff.all.order(position: 'ASC')
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'inca_subscriptions/pdfincasubscription', pdf: 'pdfincasubscription' }
    end
  end

  def billdownload
    @tariffs = Tariff.all.order(position: 'ASC')
    @q = IncaSubscription.ransack(params[:q])
    @inca_subscriptions = @q.result(distinct: true)
                            .order(name: 'ASC')
                            .where(cancellation: [false, nil])
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'inca_subscriptions/pdfbilldownload', pdf: 'pdfbilldownload' }
      format.xlsx
    end
    @totale
    @totalegenerale
    @ufficio
    @contanti
    @contantitotale
    @pos
    @postotale
    @bonifico
    @bonificototale
    @ccpostale
    @ccpostaletotale
    @altro
    @altrototale
  end

  def new
    @inca_subscription = IncaSubscription.new
    @tariffs = Tariff.all.order(position: 'ASC')
  end

  def edit
    redirect_to inca_subscriptions_path if @inca_subscription.cancellation.present?
    @tariffs = Tariff.all.order(position: 'ASC')
  end

  def create
    @inca_subscription = current_user.inca_subscriptions.build(inca_subscription_params)
    @inca_subscription.date = Date.today
    @inca_subscription.institute = current_user.institute
    @tariffs = Tariff.all.order(position: 'ASC')
    respond_to do |format|
      if @inca_subscription.save
        format.html { redirect_to inca_subscriptions_path, notice: 'Inca subscription was successfully created.' }
        format.json { render :show, status: :created, location: @inca_subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inca_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tariffs = Tariff.all.order(position: 'ASC')
    respond_to do |format|
      if @inca_subscription.update(inca_subscription_params)
        format.html { redirect_to inca_subscriptions_path, notice: 'Inca subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @inca_subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inca_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tariffs = Tariff.all.order(position: 'ASC')
    @inca_subscription.destroy
    respond_to do |format|
      format.html { redirect_to inca_subscriptions_url, notice: 'Inca subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_inca_subscription
    @inca_subscription = IncaSubscription.find(params[:id])
  end

  def inca_subscription_params
    params.require(:inca_subscription).permit(:inca_office_id, :subscription_typology_id, :customer_name,
                                              :customer_forname, :sex_id, :customer_birth_place, :customer_birth_date, :customer_fiscal_code, :customer_nationality, :customer_address, :customer_zip, :customer_city, :customer_province, :customer_phone, :customer_mobile, :customer_email, :company_vat_number, :company_fiscal_code, :company_name, :company_address, :company_zip, :company_city, :company_province, :company_typology_id, :work_qualify_id, :work_level_id, :work_contract, :work_worker_id, :work_employee_date, :work_workplace, :payment, :payment_typology_id, :category_id, :subscription_year_id, :inca_practise_id, :privacy_one_id, :privacy_two_id, :privacy_three_id, :note, :cancellation, :cancellation_reason, :name, :date, :institute, :user_id, :pdf)
  end
end

app/views/inca_subscriptions/_form_attachment.erb
<div class='card shadow'>
  <div class='card-body'>
    <%= form_with(model: inca_subscription) do |form| %>
      <% if inca_subscription.errors.any? %>
        <div id='error_explanation'>
          <h2 class='text-primary'>
            <strong>
              <%= pluralize(inca_subscription.errors.count, 'Errori') %>
              &emsp;
              Non posso salvare la Ricevuta corrente:
            </strong>
          </h2>
          <ul>
            <% inca_subscription.errors.each do |error| %>
              <li class='text-primary'><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class='row'>
        <div class='col'>
          <div class='input-group p-1'>
            <div class='input-group-prepend '>
              <div class='input-group-text input-group-text-form text-primary'>
                <i class='fas fa-file-pdf'></i>
                &nbsp;
                Allega la Ricevuta in formato PDF:&nbsp;
              </div>
            </div>
            <%= form.file_field :pdf, class:'form-control' %>
          </div>
          <span class='float-right p-2'>
            <%= link_to inca_subscriptions_path, class: 'btn btn-sm btn-outline-primary'  do %>
              <i class='fas fa-undo'></i>
              &emsp;
              <strong>Annulla</strong>
            <% end %>
            &emsp;
            <%= button_tag(type: 'submit', class: 'btn btn-outline-primary btn-sm') do %>
              <strong>
                <i class='fas fa-save'></i>
                &emsp;
                <% if current_page?(new_inca_subscription_path) %>
                  <strong>Salva</strong>
                <% else %>
                  <strong>Aggiorna</strong>
                <% end %>
              </strong>
            <% end %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/inca_subscriptions/_form_cancellation.html.erb
<div class='card shadow'>
  <div class='card-body'>
    <%= form_with(model: inca_subscription) do |form| %>
      <% if inca_subscription.errors.any? %>
        <div id='error_explanation'>
          <h2 class='text-primary'>
            <strong>
              <%= pluralize(inca_subscription.errors.count, 'Errori') %>
              &emsp;
              Non posso salvare la Ricevuta corrente:
            </strong>
          </h2>
          <ul>
            <% inca_subscription.errors.each do |error| %>
              <li class='text-primary'><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class='row'>
        <div class='col'>
          <div class='input-group p-2'>
            <h4 class='text-primary'>
              <i class='fas fa-cut'></i>
              &nbsp;
              Annullamento Sottoscrizione:&nbsp;
              &emsp;
              <%= form.check_box :cancellation, class: 'text-primary' %>
            </h4>
          </div>
          <div class='input-group p-2'>
            <div class='input-group-prepend igp-fixed-width'>
              <div class='input-group-text input-group-text-form'>
                <i class='far fa-file-alt'></i>
                &emsp;
                Motivo Annullamento:&nbsp;
              </div>
            </div>
            <%= form.text_field :cancellation_reason, class:'form-control' %>
          </div>
          <span class='float-right p-2'>
            <%= link_to inca_subscriptions_path, class: 'btn btn-sm btn-outline-primary'  do %>
              <i class='fas fa-undo'></i>
              &emsp;
              <strong>Annulla</strong>
            <% end %>
            &emsp;
            <%= button_tag(type: 'submit', class: 'btn btn-outline-primary btn-sm') do %>
              <strong>
                <i class='fas fa-save'></i>
                &emsp;
                <% if current_page?(new_inca_subscription_path) %>
                  <strong>Salva</strong>
                <% else %>
                  <strong>Aggiorna</strong>
                <% end %>
              </strong>
            <% end %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/inca_subscriptions/_show_cancelled.html.erb
<div class='col-lg-12'>
  <h3 class='text-primary p-2'>
    <i class='fas fa-receipt'></i>
    &emsp;
    Sottoscrizione INCA
    &emsp;
    <strong>
      &emsp; Numero:&nbsp;<%= @inca_subscription.name %>
      &emsp; Del:&nbsp;<%= l(@inca_subscription.date) %>
    </strong>
    <span class='float-right'>
      <%= link_to inca_subscriptions_path, class: 'btn btn-sm btn-outline-primary' do %>
        <i class='fas fa-arrow-left'></i>
        &nbsp;
        <i class='fas fa-receipt'></i>
        &emsp;
        <strong>Ritorna alla lista</strong>
      <% end %>
    </span>
  </h3>
  <hr class='hr-primary p-2'/>
  <div class='card'>
    <div class='card-body text-white text-center bg-primary p-3 shadow'>
      <h3>
        Questa Sottoscrizione &egrave; stata ANNULLATA
      </h3>
      <br/>
      per il seguente motivo:
      <br/>
      <br/>
      <strong>
        <%= @inca_subscription.cancellation_reason %>
      </strong>
    </div>
    <br/>
  </div>

app/views/inca_subscriptions/billdownload.html.erb
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='fas fa-download'></i>
      &nbsp;
      <i class='fas fa-id-card'></i>
      &emsp;
      <strong>
        Scarico Sottoscrizioni INCA
      </strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <div class='col-12'>
    <%= search_form_for @q, id: 'search-form', url: billdownload_inca_subscriptions_path do |form| %>
      <div class='input-group p-1'>
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-calendar'></i>
            &nbsp;
            Data Inizio:&nbsp;
          </div>
        </div>
        <%= form.text_field :date_gteq, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-calendar'></i>
            &nbsp;
            Data Fine:&nbsp;
          </div>
        </div>
        <%= form.text_field :date_lteq, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-building'></i>
            &nbsp;
            Ufficio:&nbsp;
          </div>
        </div>
        <%= form.collection_select(:inca_office_id_eq, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-building'></i>
            &nbsp;
            Categoria:&nbsp;
          </div>
        </div>
        <%= form.collection_select(:category_id_eq, Category.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
        &emsp;
        <%= button_tag type: 'submit', class: 'btn btn-primary', title: 'Cerca', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-search'></i>
        <% end %>
        &nbsp;
        <% if @inca_subscriptions.count > 0 %>
          &nbsp;
          <%= link_to billdownload_inca_subscriptions_path(request.parameters.merge(format: 'pdf')), class: 'btn btn-outline-primary', target: :_blank, title: 'Stampa in PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
            <i class='fas fa-print'></i>
          <% end %>
          &nbsp;
          <%= link_to billdownload_inca_subscriptions_path(request.parameters.merge(format: 'xlsx')), class: 'btn btn-outline-primary', target: :_blank, title: 'Esporta in Excel', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
            <i class='fas fa-table'></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br/>
<table class='table table-borderless table-striped'>
  <thead>
    <tr>
      <th scope='col'class='text-primary'>Numero</th>
      <th scope='col'class='text-primary'>Data</th>
      <th scope='col'class='text-primary'>Nome</th>
      <th scope='col'class='text-primary'>Cognome</th>
      <th scope='col'class='text-primary'>Codice Fiscale</th>
      <th scope='col'class='text-primary'>Categoria</th>
      <th scope='col'class='text-primary'>Ufficio</th>
      <th scope='col'class='text-primary'>Operatore</th>
    </tr>
  </thead>
  <tbody>
    <% @inca_subscriptions.each do |inca_sunscription| %>
      <tr>
        <th scope='row' class='condensedfont'><%= inca_sunscription.name %></th>
        <td class='condensedfont'><%= l(inca_sunscription.date) %></td>
        <td class='condensedfont'><%= inca_sunscription.customer_name %></td>
        <td class='condensedfont'><%= inca_sunscription.customer_forname %></td>
        <td class='condensedfont'><%= inca_sunscription.customer_fiscal_code %></td>
        <td class='condensedfont'><%= inca_sunscription.category.name %></td>
        <td class='condensedfont'><%= inca_sunscription.inca_office.name %></td>
        <td class='condensedfont'><%= inca_sunscription.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/inca_subscriptions/billdownloadnidil.html.erb
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='fas fa-download'></i>
      &nbsp;
      <i class='fas fa-id-card'></i>
      &emsp;
      <strong>
        Scarico Sottoscrizioni INCA per NIDIL
      </strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <div class='col-12'>
    <%= search_form_for @q, id: 'search-form', url: billdownloadnidil_inca_subscriptions_path do |form| %>
      <div class='input-group p-1'>
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-calendar'></i>
            &nbsp;
            Data Inizio:&nbsp;
          </div>
        </div>
        <%= form.text_field :date_gteq, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-calendar'></i>
            &nbsp;
            Data Fine:&nbsp;
          </div>
        </div>
        <%= form.text_field :date_lteq, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-building'></i>
            &nbsp;
            Ufficio:&nbsp;
          </div>
        </div>
        <%= form.collection_select(:inca_office_id_eq, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
        &emsp;
        <%= button_tag type: 'submit', class: 'btn btn-primary', title: 'Cerca', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-search'></i>
        <% end %>
        &nbsp;
        <%= link_to billdownloadnidil_inca_subscriptions_path(request.parameters.merge(format: 'pdf')), class: 'btn btn-outline-primary', target: :_blank, title: 'Stampa in PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-print'></i>
        <% end %>
        &nbsp;
        <%= link_to billdownloadnidil_inca_subscriptions_path(request.parameters.merge(format: 'xlsx')), class: 'btn btn-outline-primary', target: :_blank, title: 'Esporta in Excel', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-table'></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br/>
<table class='table table-borderless table-striped'>
  <thead>
    <tr>
      <th scope='col'class='text-primary'>Numero</th>
      <th scope='col'class='text-primary'>Data</th>
      <th scope='col'class='text-primary'>Nome</th>
      <th scope='col'class='text-primary'>Cognome</th>
      <th scope='col'class='text-primary'>Codice Fiscale</th>
      <th scope='col'class='text-primary'>Ufficio</th>
      <th scope='col'class='text-primary'>Operatore</th>
    </tr>
  </thead>
  <tbody>
    <% @inca_subscriptions.each do |inca_sunscription| %>
      <tr>
        <th scope='row' class='condensedfont'><%= inca_sunscription.name %></th>
        <td class='condensedfont'><%= l(inca_sunscription.date) %></td>
        <td class='condensedfont'><%= inca_sunscription.customer_name %></td>
        <td class='condensedfont'><%= inca_sunscription.customer_forname %></td>
        <td class='condensedfont'><%= inca_sunscription.customer_fiscal_code %></td>
        <td class='condensedfont'><%= inca_sunscription.inca_office.name %></td>
        <td class='condensedfont'><%= inca_sunscription.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/inca_subscriptions/edit.html.erb
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='fas fa-pencil-alt'></i>
      <i class='fas fa-address-card'></i>
      &emsp;
      <strong>
        Modificando la Sottoscrizione INCA
        &emsp; Numero:&nbsp;<%= @inca_subscription.name %>
        &emsp; Del:&nbsp;<%= l(@inca_subscription.date) %>
      </strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <% if @inca_subscription.pdf.attached? %>
    <%= render 'form_cancellation', inca_subscription: @inca_subscription %>
  <% elsif @inca_subscription.date.present? && !@inca_subscription.pdf.attached? %>
    <%= render 'form_attachment', inca_subscription: @inca_subscription %>
  <% else %>
    <%= render 'form', inca_subscription: @inca_subscription %>
  <% end %>
  <br/>
  <br/>
</div>

app/views/inca_subscriptions/index.html.erb
<!-- NEW  -->
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='far fa-address-card'></i>&emsp;<strong>Sottoscrizioni INCA</strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <div class='col-12'>
    <%= search_form_for @q, id: 'search-form', url: inca_subscriptions_path do |form| %>
      <div class='input-group p-1'>
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-user'></i>
            &nbsp;
            Nome:&nbsp;
          </div>
        </div>
        <%= form.text_field :customer_name_cont, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-user'></i>
            &nbsp;
            Cognome:&nbsp;
          </div>
        </div>
        <%= form.text_field :customer_forname_cont, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-id-card'></i>
            &nbsp;
            Codice Fiscale:&nbsp;
          </div>
        </div>
        <%= form.text_field :customer_fiscal_code_cont, class:'form-control' %>
        &emsp;
        <%= button_tag type: 'submit', class: 'btn btn-primary', title: 'Cerca', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-search'></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br/>
<div class='row'>
  <div class='col-12'>
    <div class='card'>
      <div class='card-body shadow'>
        <table class='table table-striped table-hover'>
          <thead>
            <tr>
              <th>Numero</th>
              <th>Data</th>
              <th>Nome</th>
              <th>Codice Fiscale</th>
              <th>Categoria</th>
              <th>Ammontare</th>
              <th>Note</th>
              <th colspan='1'></th>
            </tr>
          </thead>
          <tbody>
            <% @inca_subscriptions.each do |inca_subscription| %>
              <tr id='<%= dom_id(inca_subscription) %>' class='<%= cancelled?(inca_subscription) %>'>
                <td>
                  <%= link_to inca_subscription, title: 'Visualizza Dettaglio', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
                    <div class='circle-g200'>
                      <strong >
                        <%= inca_subscription.name %>
                      </strong>
                    </div>
                  <% end %>
                </td>
                <td><%= l(inca_subscription.date) %></td>
                <td>
                  <strong>
                    <%= inca_subscription_customer_full_name(inca_subscription) %>
                  </strong>
                </td>
                <td>
                  <strong>
                    <%= inca_subscription.customer_fiscal_code %>
                  </strong>
                </td>
                <td><%= inca_subscription.category.name %></td>
                <td><%= number_to_currency(inca_subscription.payment) %></td>
                <td><%= truncate(inca_subscription.note, length: 35) %></td>
                <td>
                  <% unless current_user.institute == 'Ufficio Amministrazione' %>
                    <% unless inca_subscription.cancellation %>
                      <%= link_to edit_inca_subscription_path(inca_subscription), title: 'Modifica la Ricevuta', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
                        <i class='fas fa-edit'></i>
                      <% end %>
                    <% end %>
                  <% end %>
                  <% if inca_subscription.user_id == current_user.id || current_user.admin == true %>
                    <% unless inca_subscription.pdf.attached? %>
                      &emsp;
                      <%= link_to inca_subscription_path(inca_subscription, format: 'pdf'), target: :_blank, title: 'Stampa la Ricevuta in PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
                        <i class='fas fa-file-pdf'></i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
  </div>
</div>
<div class='d-flex justify-content-center'>
  <%= will_paginate @inca_subscriptions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<br/>

app/views/inca_subscriptions/new.html.erb
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='fas fa-plus'></i>
      <i class='fas fa-address-card'></i>
      &emsp;
      <strong>
        Nuova Sottoscrizione INCA
      </strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <%= render 'form', inca_subscription: @inca_subscription %>
</div>

app/views/inca_subscriptions/show.html.erb
<% if @inca_subscription.cancellation %>
  <%= render 'show_cancelled' %>
<% else %>
  <%= render 'show_valid' %>
<% end %>