config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :howtos
  get 'dashboard/index'
  get 'dashboard/credits'
  get 'dashboard/statistic'
  get 'dashboard/chart'
  get 'dashboard/authorization'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :inca_receipts do
    collection do
      get :billdownload
    end
  end

  resources :inca_subscriptions do
    collection do
      get :billdownload
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all if user.present? && user.admin == true

    can :read, Howto if user.present?

    if user.institute == 'Ufficio Amministrazione'
      can :billdownload, IncaReceipt
      can :billdownload, IncaSubscription
      can :read, IncaReceipt
      can :read, IncaSubscription
      can :billdownload, GenericSubscription
      can :read, GenericSubscription
    end

    if user.institute == 'Patronato INCA'
      can :billdownload, IncaReceipt do |inca_receipt|
        inca_receipt.user == user
      end
      can :billdownload, IncaSubscription do |inca_subscription|
        inca_subscription.user == user
      end
      can :read, IncaReceipt
      can :create, IncaReceipt
      can :update, IncaReceipt do |inca_receipt|
        inca_receipt.user == user
      end
      can :read, IncaSubscription
      can :create, IncaSubscription
      can :update, IncaSubscription do |inca_subscription|
        inca_subscription.user == user
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :inca_subscriptions
  has_many :tariffs

  validates :name, presence: true
  validates :position, presence: true
end

app/models/company_typology.rb
class CompanyTypology < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/howto.rb
# frozen_string_literal: true

class Howto < ApplicationRecord
  validates :title, presence: true
  validates :topic, presence: true
  validates :description, presence: true
end

app/models/inca_office.rb
# frozen_string_literal: true

class IncaOffice < ApplicationRecord
  has_many :inca_receipts
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/inca_practise.rb
# frozen_string_literal: true

class IncaPractise < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/inca_receipt.rb
class IncaReceipt < ApplicationRecord
  belongs_to :inca_office
  belongs_to :payment_typology
  belongs_to :user

  has_one_attached :pdf

  before_create :set_name
  def set_name
    last_name = IncaReceipt.maximum(:name)
    self.name = last_name.to_i + 1
  end

  validates :date, presence: true
  validates :user_id, presence: true
  validates :institute, presence: true
  validates :inca_office_id, presence: true
  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :cancellation_reason, if: -> { cancellation == true }, presence: true
end

app/models/inca_subscription.rb
class IncaSubscription < ApplicationRecord
  belongs_to :inca_office
  belongs_to :subscription_typology
  belongs_to :sex
  belongs_to :company_typology, optional: true
  belongs_to :work_qualify, optional: true
  belongs_to :work_level, optional: true
  belongs_to :work_worker, optional: true
  belongs_to :payment_typology
  belongs_to :category
  belongs_to :subscription_year
  belongs_to :inca_practise
  belongs_to :privacy_one
  belongs_to :privacy_two
  belongs_to :privacy_three
  belongs_to :user

  has_one_attached :pdf

  before_create :set_name
  def set_name
    last_name = IncaSubscription.maximum(:name)
    self.name = last_name.to_i + 1
  end

  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true
  validates :sex_id, presence: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :customer_nationality, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :inca_office_id, presence: true
  validates :inca_practise_id, presence: true
  validates :subscription_year, presence: true
  validates :category_id, presence: true
  validates :privacy_one, presence: true
  validates :privacy_two, presence: true
  validates :privacy_three, presence: true
  validates :cancellation_reason, if: -> { cancellation == true }, presence: true
end

app/models/payment_typology.rb
# frozen_string_literal: true

class PaymentTypology < ApplicationRecord
  has_many :inca_receipts
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/privacy_one.rb
class PrivacyOne < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/privacy_three.rb
class PrivacyThree < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/privacy_two.rb
class PrivacyTwo < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/sex.rb
class Sex < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/subscription_year.rb
class SubscriptionYear < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/tariff.rb
class Tariff < ApplicationRecord
  belongs_to :category

  before_create :set_name
  def set_name
    last_name = Tariff.maximum(:name)
    self.name = last_name.to_i + 1
  end

  validates :category_id, presence: true
  validates :typology, presence: true
  validates :amount, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable

  validate :password_complexity

  def password_complexity
    if password.present? && !password.match(/^(?=.*[a-z])(?=.*[A-Z])/)
      errors.add :password, 'La password non è sufficientemente complessa'
    end
  end

  has_many :inca_receipts
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :institute, presence: true
end

app/models/work_level.rb
class WorkLevel < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/work_qualify.rb
class WorkQualify < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/models/work_worker.rb
class WorkWorker < ApplicationRecord
  has_many :inca_subscriptions

  validates :name, presence: true
  validates :position, presence: true
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpisNext</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>
  <body>
    <div class='container'>
      <% if user_signed_in? %>
        <%= render 'shared/logged' %>
      <% else %>
        <%= render 'shared/unlogged' %>
      <% end %>
    </div>
  </body>
</html>

app/views/shared/_logged.html.erb
<div class='row'>
  <div class='col-lg-12'>
    <%= render 'shared/navbar' %>
  </div>
</div>
<%= yield %>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-primary fixed-top'>
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= inline_svg('navbar_logo.svg', size: '96px * 28px', preserve_aspect_ratio: 'xMaxYMax meet') %>
  <% end %>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarColor01' aria-controls='navbarColor01' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>
  <div class='collapse navbar-collapse' id='navbarColor01'>
    <ul class='navbar-nav mr-auto'>
      <% if inca_user? %>
        <li class='nav-item dropdown'>
          <a class='nav-link dropdown' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>
            <%= inline_svg('icon_inca.svg', size: '24px * 24px', preserve_aspect_ratio: 'xMaxYMax meet') %>
            &nbsp;
            INCA
          </a>
          <div class='dropdown-menu'>
            <%= link_to new_inca_receipt_path, class: 'dropdown-item'  do %>
              <i class='fas fa-receipt'></i>&nbsp;<i class='fas fa-plus'></i>
              &nbsp;&nbsp;Nuova Ricevuta
            <% end %>
            <%= link_to inca_receipts_path, class: 'dropdown-item'  do %>
              <i class='fas fa-receipt'></i>&nbsp;<i class='fas fa-list'></i>
              &nbsp;&nbsp;Elenco Ricevute
            <% end %>
            <%= link_to billdownload_inca_receipts_path, class: 'dropdown-item'  do %>
              <i class='fas fa-receipt'></i>&nbsp;<i class='fas fa-print'></i>
              &nbsp;&nbsp;Scarico Ricevute
            <% end %>
            <div class='dropdown-divider'></div>
            <%= link_to new_inca_subscription_path, class: 'dropdown-item'  do %>
              <i class='fas fa-file-invoice'></i>&nbsp;<i class='fas fa-plus'></i>
              &nbsp;&nbsp;Nuova Sottoscrizione
            <% end %>
            <%= link_to inca_subscriptions_path, class: 'dropdown-item'  do %>
              <i class='fas fa-file-invoice'></i>&nbsp;<i class='fas fa-list'></i>
              &nbsp;&nbsp;Elenco Sottoscrizioni
            <% end %>
            <%= link_to billdownload_inca_subscriptions_path, class: 'dropdown-item'  do %>
              <i class='fas fa-file-invoice'></i>&nbsp;<i class='fas fa-print'></i>
              &nbsp;&nbsp;Scarico Sottoscrizioni
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    <ul class='navbar-nav ml-auto'>
      <li class='nav-item'>
        <%= link_to edit_user_registration_path, class: 'nav-link' do %>
          <i class='fas fa-user-circle'></i>&nbsp;&nbsp;<%= full_user %>
        <% end %>
      </li>
      <li class='nav-item dropleft'>
        <a class='nav-link dropdown' data-toggle='dropdown' href='#' role='button' aria-haspopup='true' aria-expanded='false'>
          <i class='fas fa-bars'></i>
        </a>
        <div class='dropdown-menu'>
          <% if admin? %>
            <%= link_to rails_admin_path, class: 'dropdown-item'  do %>
              <i class='fas fa-user-cog'></i>&nbsp;&nbsp;Amministrazione
            <% end %>
          <% end %>
          <% if admin? || manager? %>
            <%= link_to dashboard_statistic_path, class: 'dropdown-item'  do %>
              <i class='fas fa-chart-bar'></i>&nbsp;&nbsp;Statistiche Uffici
            <% end %>
          <% end %>
          <% if admin? || manager? %>
            <%= link_to dashboard_chart_path, class: 'dropdown-item'  do %>
              <i class='fas fa-chart-line'></i>&nbsp;&nbsp;Grafici Andamenti
            <% end %>
          <% end %>
          <%= link_to dashboard_credits_path, class: 'dropdown-item'  do %>
            <i class='fas fa-user-edit'></i>&nbsp;&nbsp;Crediti
          <% end %>
          <%= link_to howtos_path, class: 'dropdown-item'  do %>
            <i class='fas fa-book'></i>&nbsp;&nbsp;Guide
          <% end %>
          <div class='dropdown-divider'></div>
          <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
            <i class='fas fa-door-open'></i>&nbsp;&nbsp;Esci
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_unlogged.html.erb
<div class='row'>
  <div class='col-lg-12 text-center align-middle'>
    <%= yield %>
  </div>
</div>