config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :howtos
  get 'dashboard/index'
  get 'dashboard/credits'
  get 'dashboard/statistic'
  get 'dashboard/chart'
  get 'dashboard/authorization'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :inca_receipts do
    collection do
      get :billdownload
    end
  end

  resources :inca_subscriptions do
    collection do
      get :billdownload
    end
  end
end

app/models/inca_receipt.rb
class IncaReceipt < ApplicationRecord
  belongs_to :inca_office
  belongs_to :payment_typology
  belongs_to :user

  has_one_attached :pdf

  before_create :set_name
  def set_name
    last_name = IncaReceipt.maximum(:name)
    self.name = last_name.to_i + 1
  end

  validates :date, presence: true
  validates :user_id, presence: true
  validates :institute, presence: true
  validates :inca_office_id, presence: true
  validates :customer_name, presence: true
  validates :customer_forname, presence: true
  validates :customer_birth_place, presence: true
  validates :customer_birth_date, presence: true
  validates :customer_fiscal_code, presence: true
  validates :customer_address, presence: true
  validates :customer_zip, presence: true
  validates :customer_city, presence: true
  validates :customer_province, presence: true
  validates :payment, presence: true
  validates :payment_typology_id, presence: true
  validates :cancellation_reason, if: -> { cancellation == true }, presence: true
end

app/controllers/inca_receipts_controller.rb
# frozen_string_literal: true

class IncaReceiptsController < ApplicationController
  load_and_authorize_resource

  before_action :set_inca_receipt, only: %i[show edit update destroy]

  def index
    @user = current_user
    @q = IncaReceipt.ransack(params[:q])
    @inca_receipts = @q.result(distinct: true).order(name: 'DESC')
                       .paginate(page: params[:page], per_page: 10)
  end

  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'inca_receipts/pdfincareceipt', pdf: 'pdfincareceipt' }
    end
  end

  def new
    @inca_receipt = IncaReceipt.new
  end

  def edit
    redirect_to inca_receipts_path if @inca_receipt.cancellation.present?
  end

  def billdownload
    @user = current_user
    @q = IncaReceipt.ransack(params[:q])
    @inca_receipts = @q.result(distinct: true)
                       .where(cancellation: [false, nil])
                       .order(name: 'ASC')
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'inca_receipts/pdfbilldownload', pdf: 'pdfbilldownload' }
      format.xlsx
    end
    @totale
    @totalegenerale
    @ufficio
    @contanti
    @contantitotale
    @pos
    @postotale
    @bonifico
    @bonificototale
    @ccpostale
    @ccpostaletotale
    @altro
    @altrototale
  end

  def create
    @inca_receipt = current_user.inca_receipts.build(inca_receipt_params)
    @inca_receipt.date = Date.today
    @inca_receipt.institute = current_user.institute
    respond_to do |format|
      if @inca_receipt.save
        format.html { redirect_to inca_receipts_path, notice: 'Inca receipt was successfully created.' }
        format.json { render :show, status: :created, location: @inca_receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inca_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @inca_receipt.update(inca_receipt_params)
        format.html { redirect_to inca_receipts_path, notice: 'Inca receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @inca_receipt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inca_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inca_receipt.destroy
    respond_to do |format|
      format.html { redirect_to inca_receipts_url, notice: 'Inca receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_inca_receipt
    @inca_receipt = IncaReceipt.find(params[:id])
  end

  def inca_receipt_params
    params.require(:inca_receipt).permit(:inca_office_id, :customer_name,
                                         :customer_forname, :customer_birth_place,
                                         :customer_birth_date, :customer_fiscal_code,
                                         :customer_address, :customer_zip,
                                         :customer_city, :customer_province,
                                         :payment, :payment_typology_id, :note, :name,
                                         :date, :user_id, :institute, :pdf, :cancellation,
                                         :cancellation_reason)
  end
end

app/views/inca_receipts/_form.html.erb
<%= form_with(model: inca_receipt) do |form| %>
  <% if inca_receipt.errors.any? %>
    <div id='error_explanation'>
      <h2 class='text-primary'>
        <strong>
          <%= pluralize(inca_receipt.errors.count, 'Errori') %>
          &emsp;
          Non posso salvare la Ricevuta corrente:
        </strong>
      </h2>
      <ul>
        <% inca_receipt.errors.each do |error| %>
          <li class='text-primary'><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class='col-lg-6'>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-building'></i>
            &nbsp;
            <span class='text-primary'>
              Ufficio:&nbsp;
            </span>
          </div>
        </div>
        <%= form.collection_select(:inca_office_id, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-user'></i>
            &nbsp;
            <span class='text-primary'>
              Nome:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_name, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='far fa-user'></i>
            &nbsp;
            <span class='text-primary'>
              Cognome:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_forname, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-globe-europe'></i>
            &nbsp;
            <span class='text-primary'>
              Luogo di Nascita:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_birth_place, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-calendar-alt'></i>
            &nbsp;
            <span class='text-primary'>
              Data di Nascita:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_birth_date, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-credit-card'></i>
            &nbsp;
            <span class='text-primary'>
              Codice Fiscale:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_fiscal_code, class:'form-control' %>
      </div>
    </div>
    <div class='col-lg-6'>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-road'></i>
            &emsp;
            <span class='text-primary'>
              Indirizzo:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_address, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-envelope'></i>
            &emsp;
            <span class='text-primary'>
              Cap:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_zip, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-city'></i>
            &emsp;
            <span class='text-primary'>
              Comune:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_city, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-landmark'></i>
            &emsp;
            <span class='text-primary'>
              Provincia:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :customer_province, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-euro-sign'></i>
            &emsp;
            <span class='text-primary'>
              Ammontare:&nbsp;
            </span>
          </div>
        </div>
        <%= form.text_field :payment, class:'form-control' %>
      </div>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-money-check'></i>
            &nbsp;
            <span class='text-primary'>
              Tipo Pagamento:&nbsp;
            </span>
          </div>
        </div>
        <%= form.collection_select(:payment_typology_id, PaymentTypology.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-lg-12'>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form igp-fixed-width-short'>
            <i class='fas fa-clipboard'></i>
            &emsp;
            Note:&nbsp;
          </div>
        </div>
        <%= form.text_area :note, class:'form-control' %>
      </div>
      <span class='float-right p-2'>
        <%= link_to inca_receipts_path, class: 'btn btn-sm btn-outline-primary'  do %>
          <i class='fas fa-undo'></i>
          &emsp;
          <strong>Annulla</strong>
        <% end %>
        &emsp;
        <%= button_tag(type: 'submit', class: 'btn btn-outline-primary btn-sm') do %>
          <strong>
            <i class='fas fa-save'></i>
            &emsp;
            <% if current_page?(new_inca_receipt_path) %>
              <strong>Salva</strong>
            <% else %>
              <strong>Aggiorna</strong>
            <% end %>
          </strong>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/inca_receipts/_form_attachment.erb
<%= form_with(model: inca_receipt) do |form| %>
  <% if inca_receipt.errors.any? %>
    <div id='error_explanation'>
      <h2 class='text-primary'>
        <strong>
          <%= pluralize(inca_receipt.errors.count, 'Errori') %>
          &emsp;
          Non posso salvare la Ricevuta corrente:
        </strong>
      </h2>
      <ul>
        <% inca_receipt.errors.each do |error| %>
          <li class='text-primary'><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class='col'>
      <div class='input-group p-1'>
        <div class='input-group-prepend '>
          <div class='input-group-text input-group-text-form text-primary'>
            <i class='fas fa-file-pdf'></i>
            &nbsp;
            Allega la Ricevuta in formato PDF:&nbsp;
          </div>
        </div>
        <%= form.file_field :pdf, class:'form-control' %>
      </div>
      <span class='float-right p-2'>
        <%= link_to inca_receipts_path, class: 'btn btn-sm btn-outline-primary'  do %>
          <i class='fas fa-undo'></i>
          &emsp;
          <strong>Annulla</strong>
        <% end %>
        &emsp;
        <%= button_tag(type: 'submit', class: 'btn btn-outline-primary btn-sm') do %>
          <strong>
            <i class='fas fa-save'></i>
            &emsp;
            <% if current_page?(new_inca_receipt_path) %>
              <strong>Salva</strong>
            <% else %>
              <strong>Aggiorna</strong>
            <% end %>
          </strong>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/inca_receipts/_form_cancellation.html.erb
<%= form_with(model: inca_receipt) do |form| %>
  <% if inca_receipt.errors.any? %>
    <div id='error_explanation'>
      <h2 class='text-primary'>
        <strong>
          <%= pluralize(inca_receipt.errors.count, 'Errori') %>
          &emsp;
          Non posso salvare la Ricevuta corrente:
        </strong>
      </h2>
      <ul>
        <% inca_receipt.errors.each do |error| %>
          <li class='text-primary'><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class='col'>
      <div class='input-group p-2'>
        <h4 class='text-primary'>
          <i class='fas fa-cut'></i>
          &nbsp;
          Annullamento Ricevuta:&nbsp;
          &emsp;
          <%= form.check_box :cancellation, class: 'text-primary' %>
        </h4>
      </div>
      <div class='input-group p-2'>
        <div class='input-group-prepend igp-fixed-width'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-file-alt'></i>
            &emsp;
            Motivo Annullamento:&nbsp;
          </div>
        </div>
        <%= form.text_field :cancellation_reason, class:'form-control' %>
      </div>
      <span class='float-right p-2'>
        <%= link_to inca_receipts_path, class: 'btn btn-sm btn-outline-primary'  do %>
          <i class='fas fa-undo'></i>
          &emsp;
          <strong>Annulla</strong>
        <% end %>
        &emsp;
        <%= button_tag(type: 'submit', class: 'btn btn-outline-primary btn-sm') do %>
          <strong>
            <i class='fas fa-save'></i>
            &emsp;
            <% if current_page?(new_inca_receipt_path) %>
              <strong>Salva</strong>
            <% else %>
              <strong>Aggiorna</strong>
            <% end %>
          </strong>
        <% end %>
      </span>
    </div>
  </div>
<% end %>

app/views/inca_receipts/_show_cancelled.html.erb
<div class='col-lg-12'>
  <h3 class='text-primary p-2'>
    <i class='fas fa-receipt'></i>
    &emsp;
    Ricevuta Liberalit&agrave; INCA
    &emsp;
    <strong>
      &emsp; Numero:&nbsp;<%= @inca_receipt.name %>
      &emsp; Del:&nbsp;<%= l(@inca_receipt.date) %>
    </strong>
    <span class='float-right'>
      <%= link_to inca_receipts_path, class: 'btn btn-sm btn-outline-primary' do %>
        <i class='fas fa-arrow-left'></i>
        &nbsp;
        <i class='fas fa-receipt'></i>
        &emsp;
        <strong>Ritorna alla lista</strong>
      <% end %>
    </span>
  </h3>
  <hr class='hr-primary p-2'/>
  <div class='card'>
    <div class='card-body text-white text-center bg-primary p-3 shadow'>
      <h3>
        Questa Ricevuta &egrave; stata ANNULLATA
      </h3>
      <br/>
      per il seguente motivo:
      <br/>
      <br/>
      <strong>
        <%= @inca_receipt.cancellation_reason %>
      </strong>
    </div>
    <br/>
  </div>

app/views/inca_receipts/billdownload.html.erb
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='fas fa-download'></i>&nbsp;<i class='fas fa-receipt'></i>&emsp;<strong>Scarico Ricevute Liberalit&agrave; INCA</strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <div class='col-12'>
    <%= search_form_for @q, id: 'search-form', url: billdownload_inca_receipts_path do |form| %>
      <div class='input-group p-1'>
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-calendar'></i>
            &nbsp;
            Data Inizio:&nbsp;
          </div>
        </div>
        <%= form.text_field :date_gteq, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-calendar'></i>
            &nbsp;
            Data Fine:&nbsp;
          </div>
        </div>
        <%= form.text_field :date_lteq, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-building'></i>
            &nbsp;
            Ufficio:&nbsp;
          </div>
        </div>
        <%= form.collection_select(:inca_office_id_eq, IncaOffice.order('position ASC'), :id, :name, {:include_blank => true}, {:class => 'form-control'}) %>
        &emsp;
        <%= button_tag type: 'submit', class: 'btn btn-primary', title: 'Cerca', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-search'></i>
        <% end %>
        &nbsp;
        <% if @inca_receipts.count > 0 %>
          &nbsp;
          <%= link_to billdownload_inca_receipts_path(request.parameters.merge(format: 'pdf')), class: 'btn btn-outline-primary', target: :_blank, title: 'Stampa in PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
            <i class='fas fa-print'></i>
          <% end %>
          &nbsp;
          <%= link_to billdownload_inca_receipts_path(request.parameters.merge(format: 'xlsx')), class: 'btn btn-outline-primary', target: :_blank, title: 'Esporta in Excel', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
            <i class='fas fa-table'></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br/>
<table class='table table-borderless table-striped'>
  <thead>
    <tr>
      <th scope='col'class='text-primary'>Numero</th>
      <th scope='col'class='text-primary'>Data</th>
      <th scope='col'class='text-primary'>Nome</th>
      <th scope='col'class='text-primary'>Cognome</th>
      <th scope='col'class='text-primary'>Codice Fiscale</th>
      <th scope='col'class='text-primary'>Ufficio</th>
      <th scope='col'class='text-primary'>Operatore</th>
    </tr>
  </thead>
  <tbody>
    <% @inca_receipts.each do |inca_receipt| %>
      <tr>
        <th scope='row' class='condensedfont'><%= inca_receipt.name %></th>
        <td class='condensedfont'><%= l(inca_receipt.date) %></td>
        <td class='condensedfont'><%= inca_receipt.customer_name %></td>
        <td class='condensedfont'><%= inca_receipt.customer_forname %></td>
        <td class='condensedfont'><%= inca_receipt.customer_fiscal_code %></td>
        <td class='condensedfont'><%= inca_receipt.inca_office.name %></td>
        <td class='condensedfont'><%= inca_receipt.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/inca_receipts/edit.html.erb
<div class='col-lg-12'>
  <h3 class='text-primary p-2'>
    <i class='fas fa-pencil-alt'></i>
    <i class='fas fa-receipt'></i>
    &emsp;
    <strong>
      Modificando la Ricevuta Liberalit&agrave; INCA
      &emsp; Numero:&nbsp;<%= @inca_receipt.name %>
      &emsp; Del:&nbsp;<%= l(@inca_receipt.date) %>
    </strong>
  </h3>
  <hr class='hr-primary p-2'/>
  <div class='card'>
    <div class='card-body shadow'>
      <% if @inca_receipt.pdf.attached? %>
        <%= render 'form_cancellation', inca_receipt: @inca_receipt %>
      <% elsif @inca_receipt.date.present? && !@inca_receipt.pdf.attached? %>
        <%= render 'form_attachment', inca_receipt: @inca_receipt %>
      <% else %>
        <%= render 'form', inca_receipt: @inca_receipt %>
      <% end %>
    </div>
  </div>
  <br/>
  <br/>
</div>

app/views/inca_receipts/index.html.erb
<!-- NEW  -->
<div class='row'>
  <div class='col-12'>
    <h3 class='text-primary p-2'>
      <i class='fas fa-receipt'></i>&emsp;<strong>Ricevute Liberalit&agrave; INCA</strong>
    </h3>
    <hr class='hr-primary p-2'/>
  </div>
</div>
<div class='row'>
  <div class='col-12'>
    <%= search_form_for @q, id: 'search-form', url: inca_receipts_path do |form| %>
      <div class='input-group p-1'>
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-user'></i>
            &nbsp;
            Nome:&nbsp;
          </div>
        </div>
        <%= form.text_field :customer_name_cont, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='far fa-user'></i>
            &nbsp;
            Cognome:&nbsp;
          </div>
        </div>
        <%= form.text_field :customer_forname_cont, class:'form-control' %>
        &emsp;
        <div class='input-group-prepend'>
          <div class='input-group-text input-group-text-form'>
            <i class='fas fa-id-card'></i>
            &nbsp;
            Codice Fiscale:&nbsp;
          </div>
        </div>
        <%= form.text_field :customer_fiscal_code_cont, class:'form-control' %>
        &emsp;
        <%= button_tag type: 'submit', class: 'btn btn-primary', title: 'Cerca', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
          <i class='fas fa-search'></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br/>
<div class='row'>
  <div class='col-12'>
    <div class='card'>
      <div class='card-body shadow'>
        <table class='table table-striped table-hover'>
          <thead>
            <tr>
              <th>Numero</th>
              <th>Data</th>
              <th>Nome</th>
              <th>Codice Fiscale</th>
              <th>Ammontare</th>
              <th>Note</th>
              <th colspan='1'></th>
            </tr>
          </thead>
          <tbody>
            <% @inca_receipts.each do |inca_receipt| %>
              <tr id='<%= dom_id(inca_receipt) %>' class='<%= cancelled?(inca_receipt) %>'>
                <td>
                  <%= link_to inca_receipt, title: 'Visualizza Dettaglio', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
                    <div class='circle-g200'>
                      <strong >
                        <%= inca_receipt.name %>
                      </strong>
                    </div>
                  <% end %>
                </td>
                <td><%= l(inca_receipt.date) %></td>
                <td>
                  <strong>
                    <%= inca_receipt_customer_full_name(inca_receipt) %>
                  </strong>
                </td>
                <td>
                  <strong>
                    <%= inca_receipt.customer_fiscal_code %>
                  </strong>
                </td>
                <td><%= number_to_currency(inca_receipt.payment) %></td>
                <td><%= truncate(inca_receipt.note, length: 35) %></td>
                <td>
                  <% unless current_user.institute == 'Ufficio Amministrazione' %>
                    <% unless inca_receipt.cancellation %>
                      <%= link_to edit_inca_receipt_path(inca_receipt), title: 'Modifica la Ricevuta', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
                        <i class='fas fa-edit'></i>
                      <% end %>
                    <% end %>
                  <% end %>
                  <% if inca_receipt.user_id == current_user.id || current_user.admin == true %>
                    <% unless inca_receipt.pdf.attached? %>
                      &emsp;
                      <%= link_to inca_receipt_path(inca_receipt, format: 'pdf'), target: :_blank, title: 'Stampa la Ricevuta in PDF', 'data-toggle' => 'tooltip', 'data-placement' => 'bottom' do %>
                        <i class='fas fa-file-pdf'></i>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
  </div>
</div>
<div class='d-flex justify-content-center'>
  <%= will_paginate @inca_receipts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<br/>

app/views/inca_receipts/new.html.erb
<div class='col-lg-12'>
  <h3 class='text-primary p-2'>
    <i class='fas fa-plus'></i>
    <i class='fas fa-receipt'></i>
    &emsp;
    <strong>
      Nuova Ricevuta Liberalit&agrave; INCA
    </strong>
  </h3>
  <hr class='hr-primary p-2'/>
  <div class='card'>
    <div class='card-body shadow'>
      <%= render 'form', inca_receipt: @inca_receipt %>
    </div>
  </div>
  <br/>
  <br/>
</div>

app/views/inca_receipts/show.html.erb
<% if @inca_receipt.cancellation %>
  <%= render 'show_cancelled' %>
<% else %>
  <%= render 'show_valid' %>
<% end %>