config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboard#index'

  resources :howtos
  get 'dashboard/index'
  get 'dashboard/credits'
  get 'dashboard/statistic'
  get 'dashboard/chart'
  get 'dashboard/authorization'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :inca_receipts do
    collection do
      get :billdownload
    end
  end

  resources :inca_subscriptions do
    collection do
      get :billdownload
    end
  end
end

app/models/howto.rb
# frozen_string_literal: true

class Howto < ApplicationRecord
  validates :title, presence: true
  validates :topic, presence: true
  validates :description, presence: true
end

app/controllers/howtos_controller.rb
# frozen_string_literal: true

class HowtosController < ApplicationController
  load_and_authorize_resource

  before_action :set_howto, only: %i[show edit update destroy]

  def index
    @howtos = Howto.all.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @howto = Howto.new
    # authorize! :create, @howto
  end

  def edit
    # authorize! :update, @howto
  end

  def create
    @howto = Howto.new(howto_params)

    respond_to do |format|
      if @howto.save
        format.html { redirect_to @howto, notice: 'Howto was successfully created.' }
        format.json { render :show, status: :created, location: @howto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @howto.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @howto.update(howto_params)
        format.html { redirect_to @howto, notice: 'Howto was successfully updated.' }
        format.json { render :show, status: :ok, location: @howto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @howto.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @howto.destroy
    respond_to do |format|
      format.html { redirect_to howtos_url, notice: 'Howto was successfully destroyed.' }
      format.json { head :no_content }
    end
    # authorize! :destroy, @howto
  end

  private

  def set_howto
    @howto = Howto.find(params[:id])
  end

  def howto_params
    params.require(:howto).permit(:title, :topic, :description)
  end
end

app/views/howtos/_form.html.erb
<%= form_with(model: howto) do |form| %>
  <% if howto.errors.any? %>
    <div id="error_explanation">
      <h2 class='text-primary'>
        <strong>
          <%= pluralize(howto.errors.count, "Errori") %>
          &emsp;
          Non posso salvare la Guida corrente:
        </strong>
      </h2>
      <ul>
        <% howto.errors.each do |error| %>
          <li class='text-primary'><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='input-group p-2'>
    <div class='input-group-prepend '>
      <div class='input-group-text input-group-text-form igp-fixed-width'>
        <i class='fas fa-book'></i>
        &emsp;
        Titolo:&nbsp;
      </div>
    </div>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class='input-group p-2'>
    <div class='input-group-prepend '>
      <div class='input-group-text input-group-text-form igp-fixed-width'>
        <i class='fas fa-book-open'></i>
        &emsp;
        Argomento:&nbsp;
      </div>
    </div>
    <%= form.text_field :topic, class: 'form-control' %>
  </div>
  <div class='input-group p-2'>
    <div class='input-group-prepend '>
      <div class='input-group-text input-group-text-form igp-fixed-width'>
        <i class='fas fa-align-left'></i>
        &emsp;
        Descrizione:&nbsp;
      </div>
    </div>
    <%= form.text_area :description, class: 'form-control' %>
  </div>
  <hr/>
  <span class='float-right'>
    <% if current_page?(new_howto_path) %>
      <%= button_tag(type: 'submit', class: 'btn btn-sm btn-primary', title: 'Salva', 'data-toggle' => 'tooltip', 'data-placement' => 'top') do %>
        <i class='fas fa-save'></i>
        &emsp;
        <strong>
          Salva
        </strong>
      <% end %>
    <% else %>
      <%= button_tag(type: 'submit', class: 'btn btn-sm btn-primary', title: 'Salva', 'data-toggle' => 'tooltip', 'data-placement' => 'top') do %>
        <i class='fas fa-save'></i>
        &emsp;
        <strong>
          Aggiorna
        </strong>
      <% end %>
    <% end %>
  </span>
  <br/>
  &emsp;
<% end %>

app/views/howtos/_howto.html.erb
<%= content_tag :card, id: dom_id(howto), class: 'card m-2 shadow' do %>
  <div class='card-body'>
    <div class='row'>
      <div class='col'>
        <i class='fas fa-book'></i>&nbsp;
        <%= link_to howto.title, howto, class: 'text-secondary' %>
      </div>
      <div class='col'>
        <i class='fas fa-book-open'></i>&nbsp;
        <%= howto.topic %>
      </div>
    </div>
    <div class='row'>
      <div class='col'>
        <hr/>
        <%= howto.description.truncate(300) %>
      </div>
    </div>
  </div>
<% end %>

app/views/howtos/edit.html.erb
<div class='col-lg-10 offset-1'>
  <h4 class='text-primary p-2'>
    <i class='fas fa-pencil-alt'></i>
    &nbsp;
    <i class='fas fa-book'></i>
    &emsp;
    <strong>Modificando la Guida <small>(<%= @howto.title %>)</small></strong>
    <span class='float-right'>
      <%= link_to howtos_path, class: 'btn btn-sm btn-primary' do %>
        <i class='fas fa-arrow-left'></i>
        &nbsp;
        <i class='fas fa-book'></i>
        &emsp;
        <strong>Ritorna alla lista</strong>
      <% end %>
    </span>
  </h4>
  <hr class='hr-primary p-2'/>
  <div class='card shadow'>
    <div class='card-body'>
      <%= render 'form', howto: @howto %>
    </div>
  </div>
</div>

app/views/howtos/index.html.erb
<div class='col-lg-10 offset-1'>
  <h3 class='text-primary p-2'>
    <i class='fas fa-book'></i>&emsp;<strong>Guide</strong>
    <span class='float-right'>
      <%= link_to new_howto_path, class: 'btn btn-sm btn-primary'  do %>
        <i class='fas fa-book'></i>&nbsp;<i class='fas fa-plus'></i>
        &emsp;
        <strong>Creare una Nuova Guida</strong>
      <% end %>
    </span>
  </h3>
  <hr class='hr-primary p-2'/>
  <%= render @howtos %>
  <br/>
  <div class='col-lg-6 offset-3 text-center'>
    <%= will_paginate @howtos, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
  <br/>
</div>
</div>

app/views/howtos/new.html.erb
<div class='col-lg-10 offset-1'>
  <h4 class='text-primary p-2'>
    <i class='fas fa-pencil-alt'></i>
    &nbsp;
    <i class='fas fa-book'></i>
    &emsp;
    <strong>Creando una Nuova Guida</strong>
    <span class='float-right'>
      <%= link_to howtos_path, class: 'btn btn-sm btn-primary' do %>
        <i class='fas fa-arrow-left'></i>
        &nbsp;
        <i class='fas fa-book'></i>
        &emsp;
        <strong>Ritorna alla lista</strong>
      <% end %>
    </span>
  </h4>
  <hr class='hr-primary p-2'/>
  <div class='card shadow'>
    <div class='card-body'>
      <%= render 'form', howto: @howto %>
    </div>
  </div>
</div>

app/views/howtos/show.html.erb
<div class='col-lg-10 offset-1'>
  <span class='float-right'>
    <%= link_to howtos_path, class: 'btn btn-sm btn-primary' do %>
      <i class='fas fa-arrow-left'></i>
      &nbsp;
      <i class='fas fa-book'></i>
      &emsp;
      <strong>Ritorna alla lista</strong>
    <% end %>
    &emsp;
    <%= link_to edit_howto_path(@howto), class: 'btn btn-sm btn-primary' do %>
      <i class='fas fa-pencil-alt'></i>
      &nbsp;
      <i class='fas fa-book'></i>
      &emsp;
      <strong>Modifica la Guida</strong>
    <% end %>
    &emsp;
    <%= link_to @howto, method: :delete, data: { confirm: 'Sei sicuro di voler Eliminare il Record Corrente?' }, class: 'btn btn-sm btn-primary' do %>
      <i class='fas fa-trash-alt'></i>
      &nbsp;
      <i class='fas fa-book'></i>
      &emsp;
      <strong>Elimina la Guida</strong>
    <% end %>
  </span>
  <br/>
  &emsp;
  <div class='card shadow'>
    <div class='card-body'>
      <p>
        <i class='fas fa-book'></i>&nbsp;
        Titolo:&emsp;
        <strong>
          <%= @howto.title %>
        </strong>
        <span class='float-right'>
          <i class='fas fa-book-open'></i>&nbsp;
          Argomento:&emsp;
          <strong>
            <%= @howto.topic %>
          </strong>
        </span>
      </p>
      <hr class='hr-secondary'/>
      <p>
        <strong>Descrizione:</strong> <br/>
        <%= @howto.description %>
      </p>
    </div>
  </div>
</div>